#!/usr/bin/env python3
"""Self-host the app's Google Fonts into fonts/ and emit the @font-face CSS.

Why this exists: the fonts used to load from fonts.googleapis.com (+ the woff2
from fonts.gstatic.com). Even loaded non-render-blocking (R2-1), that's two
third-party origins the page must preconnect — and a production PageSpeed run
(2026-07-16) showed the LCP is a basemap tile that wants those preconnect slots
for the CARTO tile shards, plus a small CLS from the cross-origin font swap
landing late. Self-hosting fixes both: it drops the two font preconnects (freeing
them for the tile shards) and, served same-origin + service-worker-precached,
the font arrives early enough that the swap barely shifts layout.

This fetches Google's own per-subset woff2 (latin + latin-ext — civic officeholder
names need the latin-ext accents), dedupes by URL (Big Shoulders Display and Inter
are variable fonts, one file per subset shared across weights), writes them to
fonts/, and prints the @font-face CSS to stdout. Paste that block into index.html's
<style> (just after the inlined Leaflet CSS), between the SELF-HOSTED FONTS markers
— same "inline third-party CSS with a regenerate comment" pattern as the Leaflet
block. Re-run on any family/weight change and re-paste.

Like build_embedded_boundaries.py / build_legislative_boundaries.py this is an
occasional OPERATOR step, not weekly CI. Prerequisite: curl (through the proxy).

Usage:
    python3 scripts/build_fonts.py            # -> fonts/*.woff2 + @font-face on stdout
    python3 scripts/build_fonts.py > /tmp/fontface.css
"""

import os
import re
import subprocess
import sys
from collections import defaultdict

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS_DIR = os.path.join(REPO_ROOT, "fonts")
# The exact families/weights the app's --font-display / --font-body / --font-mono
# reference. Keep in lockstep with those CSS vars in index.html.
GFONTS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Big+Shoulders+Display:wght@600;800;900"
    "&family=Inter:wght@400;500;600;700"
    "&family=IBM+Plex+Mono:wght@400;500"
    "&display=swap"
)
# A real browser UA so Google serves woff2 (not the legacy ttf it hands old UAs).
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")
SUBSETS = ("latin", "latin-ext")


def slug(fam):
    return re.sub(r"[^a-z0-9]+", "-", fam.lower()).strip("-")


def fetch_css():
    return subprocess.run(
        ["curl", "-sS", "--fail", "--max-time", "60", "-A", UA, GFONTS_URL],
        check=True, capture_output=True,
    ).stdout.decode("utf-8")


def parse_faces(css):
    faces = []
    for sub, body in re.findall(r"/\* ([a-z-]+) \*/\s*@font-face \{([^}]*)\}", css):
        if sub not in SUBSETS:
            continue
        faces.append({
            "sub": sub,
            "fam": re.search(r"font-family: '([^']+)'", body).group(1),
            "wght": re.search(r"font-weight: (\d+)", body).group(1),
            "style": (re.search(r"font-style: (\w+)", body) or [None, "normal"])[1],
            "url": re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1),
            "urange": re.search(r"unicode-range: ([^;]+);", body).group(1).strip(),
        })
    if not faces:
        raise RuntimeError("no latin/latin-ext @font-face blocks parsed — did the CSS format change?")
    return faces


def name_files(faces):
    """One local filename per UNIQUE url. A family+subset served by a single url
    is a variable font -> <slug>-<subset>.woff2; distinct urls per weight (static)
    -> <slug>-<weight>-<subset>.woff2."""
    urls_by_famsub = defaultdict(set)
    for f in faces:
        urls_by_famsub[(f["fam"], f["sub"])].add(f["url"])
    url_name = {}
    for f in faces:
        variable = len(urls_by_famsub[(f["fam"], f["sub"])]) == 1
        url_name[f["url"]] = (
            "%s-%s.woff2" % (slug(f["fam"]), f["sub"]) if variable
            else "%s-%s-%s.woff2" % (slug(f["fam"]), f["wght"], f["sub"])
        )
    return url_name


def main():
    css = fetch_css()
    faces = parse_faces(css)
    url_name = name_files(faces)

    os.makedirs(FONTS_DIR, exist_ok=True)
    for url, name in sorted(set(url_name.items())):
        dest = os.path.join(FONTS_DIR, name)
        subprocess.run(["curl", "-sS", "--fail", "--max-time", "60", url, "-o", dest], check=True)
        print("  %s (%d b)" % (name, os.path.getsize(dest)), file=sys.stderr)
    print("%d faces, %d unique woff2 in fonts/" % (len(faces), len(set(url_name.values()))), file=sys.stderr)

    out = ["/* ==== SELF-HOSTED FONTS:BEGIN — generated by scripts/build_fonts.py; do",
           "   NOT hand-edit. Was fonts.googleapis.com; self-hosted so the two font",
           "   preconnects free up for the basemap tile shards (PSI LCP) and the",
           "   same-origin + SW-precached woff2 lands early enough to avoid the swap",
           "   CLS. Re-run scripts/build_fonts.py and re-paste on a font change. ==== */"]
    for f in faces:
        out += ["@font-face {",
                "  font-family: '%s';" % f["fam"],
                "  font-style: %s;" % f["style"],
                "  font-weight: %s;" % f["wght"],
                "  font-display: swap;",
                "  src: url(fonts/%s) format('woff2');" % url_name[f["url"]],
                "  unicode-range: %s;" % f["urange"],
                "}"]
    out.append("/* ==== SELF-HOSTED FONTS:END ==== */")
    print("\n".join(out))


if __name__ == "__main__":
    main()
